# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-06-30 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='tb_users',
        ),
    ]
