# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-18 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '待发货'), (4, '待评价'), (5, '已完成'), (6, '已取消'), (1, '待支付'), (3, '待收货')], default=1, verbose_name='订单状态'),
        ),
    ]
