# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190718_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(2, '支付宝'), (1, '货到付款')], default=1, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(2, '待发货'), (5, '已完成'), (6, '已取消'), (4, '待评价'), (3, '待收货'), (1, '待支付')], default=1, verbose_name='订单状态'),
        ),
    ]
